- mvt/ios/cli.py
SYSDIAGNOSE_MODULES is not present nor is it referenced elsewhere.  I assume this is a dangling reference to something that was removed?
It's causing a NamError exception when running check-iocs via the iOS CLI.
> [iOS CLI] Remove non-existent SYSDIAGNOSE_MODULES reference

- mvt/ios/cli.py
If `--password|-p` is specified with no argument, prompt the user to enter a password interactively.
(clone of #13)
> Prompt for password if none is given

- mvt/android/download_apks.py
- mvt/android/modules/adb/base.py
This improves upon the [pull request by goshawk22](https://github.com/mvt-project/mvt/pull/20) that broke `mvt.android.modules.adb.whatsapp` and `mvt.android.modules.adb.sms`.
See details in the commit description.
> Fix download of APKs that require root privileges #2

- mvt/android/modules/adb/base.py
"which su" will return the path of the su binary, or it will return nothing. 
The python boolean of a string with something in it (such as the path of the su binary), will be True.
An empty string (where there is no su binary) will be False.
This fixes Issue #9
> Better check for if device has root

- mvt/android/modules/adb/whatsapp.py
- mvt/common/module.py
When using WhatsApp module, parsing WhatsApp database will fail if one message contains a link and a thumb image : 
```bash
$ mvt-android check-adb  -m Whatsapp -o out
14:18:16 INFO     [mvt.android.cli] Checking Android through adb bridge                                                                                                                                                                    
INFO     [mvt.android.modules.adb.whatsapp] Running module Whatsapp...                                                                                                                                                            
INFO     [mvt.android.modules.adb.whatsapp] Extracted a total of 92 WhatsApp messages containing links …
```
> [ADB] Fix WhatsApp database parsing (thumb_image)

- README.md
Changed "evidences" to "evidence". Changed "understanding basics" to "understanding the basics". Changed "command line" to "command-line"
> fix: readme grammar

- mvt/ios/modules/fs/chrome_history.py
Indicators are actually not checked for Chrome history records.  
This pull request adds the `check_indicators` method to the `ChromeHistory` class.
> Chrome History - Cheking extracted URLs against indicators.

- mvt/android/modules/adb/base.py
- mvt/android/modules/adb/sms.py
On my phone, the SMS database is located at `/data/data/com.android.providers.telephony/databases/mmssms.db` instead of `/data/data/com.google.android.apps.messaging/databases/bugle_db`.
The format of the base itself is also different, so the SQL query had to be adapted :
Original SQL query :
```sql
SELECT 
ppl.normalized_destination AS number,
p.timestamp AS timestamp,
CASE WHEN m.sender_id IN 
(SELECT _id FROM participants WHERE contact_id=-1)
THEN 2 ELSE 1 END incoming, p.text AS text 
FROM messages m, conversations c, parts p,
participants ppl, conversation_participants cp
WHERE (m.conversation_id = c._id)
AND (m._id = p.message_id)
AND (cp.conversation_id = c._id)
AND (cp.participant_id = ppl._id);
```
New SQL query added :
```sql
SELECT 
address AS number,
date_sent AS timestamp, …
```
> [ADB] Handle SMS base in mmssms.db instead of bugle_db

- README.md
- docs/ios/backup/check.md
- mvt/ios/cli.py
- mvt/ios/keyutils.py
The `extract-key` command outputs an iTunes backup decryption key to a file (for use with `decrypt-backup -k`) or to STDOUT:
```
$ mvt-ios extract-key ./MobileSync/Backup/deadbeefdeadbeefdeadbeefdeadbeefdeadbeef/
Backup password: [password]
00:00:00 INFO     [mvt.ios.keyutils] Extracted decryption key.
INFO     [mvt.ios.keyutils] Decryption key for backup at path
MobileSync/Backup/deadbeefdeadbeefdeadbeefdeadbeefdeadbeef/ is:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ mvt-ios extract-key ./MobileSync/Backup/deadbeefdeadbeefdeadbeefdeadbeefdeadbeef/ -k decryption.key
Backup password: [password]
00:00:00 INFO     [mvt.ios.keyutils] Extracted decryption key.
INFO     [mvt.ios.keyutils] Wrote decryption key for backup at path …
```
> Add `extract-key` command for viewing and saving iOS backup decryption keys

- docs/iocs.md
This offers generic documentation, to show how MVT can be used with
arbitrary STIX-formatted IOCs, while still pointing users at some
known-to-be-useful sample files.
This aims to be more malware-agnostic than #85.  It might also help search engines recognize the relevance of MVT to people who are already searching for STIX-formatted IOCs.
> Describe how to use and find IOCs

- docs/ios/backup/check.md
- mvt/ios/cli.py
Specifying the password on the command line with `--password XXX`
leaves the password itself visible to any process on the machine which
can scan the process table.
On some systems (including common GNU/Linux distributions) this
visibility is possible by default.
This change should make it possible to offer the password without
putting it into the process table; rather, the user puts the password
in the environment, and specifies the name of the environment
variable, like so:
```
$ export IDEV_BKUP_PASS=WronglySconeRoundnessUnruffled
$ mvt-ios decrypt-backup -d /path/to/dest --passenv IDEV_BKUP_PASS /path/to/data/XXXXXXXX-YYYYYYYYYYYYYYY/
$ unset IDEV_BKUP_PASS
```
I tried first putting the password itself as a UTF-8-encoded string in
a file, and then pointing the `--key-file` option at …
> mvt-ios decrypt-backup: Enable pulling password from the environment.

- docs/ios/backup/libimobiledevice.md
In this stage, the user is likely to want to run `idevicebackup2` in
interactive mode, so clearly specify the `-i` flag in the right place
(just dropping `-i` at the end of the command does not work as
expected -- i think `idevicebackup2 backup encryption on -i` tries to
set the password to `-i`).
More importantly, note that resetting the password by resetting all
the settings runs a risk of removing some of the forensic information.
Etienne identified a file that he thought was wiped as a result of
this in the call this morning, but I don't remember which file it was.
Maybe `id_status_cache.json` ?  If you have more concrete info, please
add it here too!
> Update libimobiledevice docs about backup password reset

- mvt/ios/modules/fs/base.py
If file_path has any whitespace or shell metacharacters in it, then
the invocation of subprocess.call would be likely to break (or even
accidentally execute code, depending on how perverse the pathnames
are).
It's generally a good plan to avoid shell=True for subprocess.call
where you can lay out the arguments deliberately in python.  This one
looks relatively straightforward (but note, i have not tested it,
sorry!)
> Avoid breakage with paths with unusual names

- mvt/ios/modules/fs/base.py
In b2afce5c79b9305028e1ff7bb226a0ef3d9affc5, the db filename is
wrapped in double-quotes when passing it to the sqlite3 tool's
`.clone` helper command.
For parsing safety, we avoid performing this cleanup if the filename
itself has a double-quote character in it.  Otherwise, a malformed
filename could lead to arbitrary injection into the sqlite3 command.
In be2468004613fe3a40dcf6c8acebd8c866d635d3, the sqlite3 wrapping
changes to single-quotes.  Either the safety check should be amended
to block pathnames with single-quotes, or the sqlite3 wrapping should
revert to double-quotes.
I opted for the latter here because i think single-quotes are more
likely than double-quotes to show up in pathnames (e.g. a folder named
"Daniel's files"), but either change would be fine, of course.
> mvt-ios sqlite3 db recovery: fix quoting sent to sqlite3 .clone

- mvt/ios/decrypt.py
The two most common reasons that `mvt-ios decrypt-backup` can fail are
wrong passwords and not pointing to an actual backup.
We can distinguish these cases based on the kinds of errors thrown
from iOSbackup (at least for the current versions that i'm testing
with).
When we encounter those particular exceptions, just report a simple
summary and don't overwhelm the user with a backtrace.  If we
encounter an unexpected exception, leave the reporting as-is.
Closes: #28, #36
> mvt-ios decrypt-backup: Improve error messages for known cases

- mvt/ios/cli.py
- mvt/ios/decrypt.py
This series improves on the error handling for `mvt-ios decrypt-backup`, in particular:
- making sure that a failure gets reported as a failure by returning a non-zero
- implementing the friendlier path-finding logic outlined in #147
> mvt-ios decrypt-backup: friendlier error handling

- mvt/common/module.py
Be more explicit about that nothing was found. Otherwise, users might be wondering if the program has terminated successfully or if something failed.
The last line is new:
```
$ mvt-android check-backup --iocs ~/android-analyse/pegasus.stix2 ~/android-analyse/dominik-android-backup --output ~/android-analyse/dominik-android-backup_out
12:19:15 INFO     [mvt.android.cli] Checking ADB backup located at: /home/dominik/android-analyse/dominik-android-backup     
INFO     [mvt.android.cli] Loading indicators from provided file at /home/dominik/android-analyse/pegasus.stix2     
INFO     [mvt.android.modules.backup.sms] Running module SMS...                                                    
INFO     [mvt.android.modules.backup.sms] Processing SMS backup file at …
```
> Log if there was no detection made by the module

- docs/ios/records.md
Added availability details for backup records which require encryption or aren't available anymore in recent iOS versions.
**Only available in encrypted backups:**
* `calls`
* `interaction_c`
* `safari_browser_state`
* `safari_history`
**Only available before iOS 14.7.0:**
* `id_status_cache`
> Added availability details to records.md

- Dockerfile
Limiting multiple layers to lift docker size (from 883MB to 794MB) and follow best practices (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers)
> Dockerfile lifting

- docs/android/backup.md
- docs/android/download_apks.md
- docs/install.md
- docs/ios/backup/itunes.md
- docs/ios/methodology.md
Just some esthetic fixes to uniform documentation (i.e. MVT is always capitalized)
> Some esthetic fixes to documentation

- Dockerfile
This minor patch creates a .android directory and generates security keys. 
This patch fixes the following error: 
```
Traceback (most recent call last):
File "/usr/local/bin/mvt-android", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
return …
```
> Create adb keys (Fixes #165)

- docs/ios/records.md
- mvt/ios/modules/mixed/__init__.py
- mvt/ios/modules/mixed/osanalytics_addaily.py
This PR adds a new module, `OSAnalyticsADDAILY`, which will collect and parse the file `com.apple.osanalytics.addaily.plist`.
This file is a plist which contains records similar to this :
```
...
<key>coreduetd</key>
<array>
<date>2020-10-27T13:56:40Z</date>
<real>3232269</real>
<real>6847771</real>
<real>82337</real>
<real>43704</real>
</array>
...
```
I could not find documentation for this file online, but comparing it with NetUsage.sqlite and DataUsage.sqlite allowed me to confirm that the `real` attributes were for `wifi_in`, `wifi_out`, `wwan_in` and `wwan_out`.
Adding this module will :
- look for malicious processes in a new file (sometimes processes are only seen in this file and not in DataUsage.sqlite or NetUsage.sqlite)
- add a new information source for network usage, which …
> New artefact, com.apple.osanalytics.addaily.plist

- mvt/ios/modules/net_base.py
`check_manipulated` will check for missing or manipulated DB entries.
However, if `proc["proc_name"]` is not defined, `len(proc["proc_name"])` in `_find_suspicious_processes` ([here](https://github.com/mvt-project/mvt/blob/e5f2aa3c3d651b1fe8a0401cce82d3eeb6d7e178/mvt/ios/modules/net_base.py#L148)) will throw out an error (as `proc["proc_name"] is None`)
This error will interrupt the whole module, stopping the parsing of the file and not launching `check_manipulated()` or `find_deleted()`.
This patch makes sure this does not happen by checking that `proc["proc_name"]` is not `None`
> fix error for manipulated entries in DataUsage/NetUsage

- mvt/ios/modules/mixed/idstatuscache.py
- mvt/ios/modules/mixed/locationd.py
- mvt/ios/modules/mixed/safari_browserstate.py
For IDStatusCache, LocationdClients and SafariBrowserState modules running on a filesystem, when multiple *_ROOT_PATHS are valid, using `_find_ios_database` will only set as `self.file_path` (and therefore process) the first valid path found.
However, those files can exist at multiple locations, and they should all be parsed.
This can miss IDStatusCache, LocationdClients and SafariBrowserState entries if an empty or incorrect file is at the first indicated path, and valid and additional entries are located at the other paths.
For SafariBrowserState, the `SAFARI_BROWSER_STATE_BACKUP_IDS` was removed as the patch uses `_get_backup_files_from_manifest` instead.
(this fix is similar to what is done for Netusage, SafariFavicon, SafariHistory etc. ; all modules that use …
> fix multi path/file issue

- docs/ios/install.md
PR to update the url in the provided docs for iOS.
The link provided for libimobiledevice in  https://docs.mvt.re/en/latest/ios/install.html shows a warning due to an expired certificate.
> docs: update libimobiledevice url in docs

- docs/ios/records.md
- mvt/common/indicators.py
- mvt/ios/modules/fs/__init__.py
- mvt/ios/modules/fs/shutdown.py
This PR adds a new module, `ShutdownLog`, which will collect and parse the shutdown.log file, located at `private/var/db/diagnostics/shutdown.log`
When shutting down an iPhone, a SIGTERM will be sent to all processes running. The `shutdown.log` file will log any process (with its pid and path) that did not shut down after the SIGTERM was sent, with the timestamp at which the SIGTERM was sent.
`shutdown.log` is a multiline log file which contains records similar to this :
```
SIGTERM: [<TIMESTAMP>] All buffers flushed
After X.XXs, these clients are still here:
remaining client pid: 1 (<path1>)
remaining client pid: 2 (<path2>)
remaining client pid: 3 (<path3>)
remaining client pid: 4 (<path4>)
After X.XXs, these clients are still here:
remaining client pid: 1 (<path1>)
remaining client …
```
> New artefact, shutdown.log

- mvt/ios/modules/backup/configuration_profiles.py
This PR will fix some errors that would occur when parsing `configurationprofiles` files.
This will fix two bugs :
- If the plist file is empty, `plist.load` ([here](https://github.com/mvt-project/mvt/blob/356bddc3af79677792f1d7554e4f9f09e1948adf/mvt/ios/modules/backup/configuration_profiles.py#L30)) would fail, which will make the entire module fail
- If the plist contains bytes, they need to be b64 encoded. This was done for `SignerCerts`, but also had to be done for some other fields.
> Fix ConfigurationProfiles

- mvt/android/modules/adb/base.py
Some adb commands (like `dumpsys`) are very slow and the default timeout is "only" 10s. 
A timeout of 200 seconds is chosen completely at random - works on my phone 🤷
Fixes https://github.com/mvt-project/mvt/issues/113
Fixes https://github.com/mvt-project/mvt/issues/228
> Bump adb read timeout

- .gitignore
- dev/mvt-android
- mvt/android/download_apks.py
- mvt/android/modules/adb/dumpsys_batterystats.py
- mvt/android/modules/adb/dumpsys_full.py
- mvt/android/modules/adb/dumpsys_packages.py
- mvt/android/modules/adb/dumpsys_procstats.py
- mvt/android/modules/adb/logcat.py
- mvt/common/indicators.py
- mvt/common/module.py
- mvt/ios/decrypt.py
- mvt/ios/modules/fs/shutdownlog.py
- mvt/ios/modules/fs/version_history.py
- tests/artifacts/generate_stix.py
Not every system uses utf-8 as a default encoding for `open()`, so it is better to write argument `encoding="utf-8"` when using `open()` function in Python. I've tried to find a way to set utf-8 as a default encoding for opening files, but, there is no possibility to do this.
Also, this should fix this errors like this one:
> Make utf-8 as a default for open()

- .gitignore
- mvt/ios/modules/backup/configuration_profiles.py
Certain fields in MDM configuration profile information were not properly base64 encoded when saving output to JSON, causing errors. This is now fixed and tested to work with current Microsoft InTune managed devices.
> base64 encoding fixes in ConfigurationProfiles module

- docs/iocs.md
The current URL listed in the docs is 404, this is the fixed URL.
> Fix stalkerware STIX URL

- mvt/android/cli.py
- mvt/common/indicators.py
- mvt/common/logo.py
- mvt/common/updates.py
- mvt/ios/cli.py
- setup.cfg
At launch MVT will now be able to check whether there are updates to indicators files as defined in a newly created file located at:
https://github.com/mvt-project/mvt-indicators/blob/main/indicators.yaml
The automatic check will now be executed at a minimum frequency of 12 hours.
> Added process to automatically check for indicators updates

- mvt/android/cmd_download_apks.py
I tried to download apks from my smartphone via serial but it didn't work so I noticed that the Package object was not receiving the string serial, so when _adb_connect() was called from Packages run method the serial variable was set to None and for this reason the connection was not established.
> Fixed cmd_download_apks serial connection bug

- docs/ios/backup/libimobiledevice.md
`backup` should be removed from those commands, otherwise it will create a backup in "encryption" or "changepw" directories.
> Fixed idevicebackup2 syntax

- Dockerfile
- docs/docker.md
This PR improves the Dockerfile:
* Switch the base image to LTS 22.04
* Use the native `adb` package (available on arm64 too)
* Docker doc improvements
> Dockerfile improvements, support arm64 builds

- docs/android/backup.md
- docs/ios/records.md
- mvt/android/modules/adb/sms.py
- mvt/android/modules/backup/sms.py
- mvt/android/parsers/backup.py
- mvt/ios/modules/mixed/sms.py
- mvt/ios/modules/mixed/whatsapp.py
One initial decision with MVT was to only extract messages from SMS and WhatsApp there were containing links, but this is getting a problem in some investigation because messages from an attack could be missed during manual review. 
Here is a MR that change that and extract all messages.
> Extract all messages from SMS and WhatsApp

- mvt/common/module.py
Crashing when trying to create "timeline.csv" file, because some special character. 
The error was the following
```
Traceback (most recent call last):
File "/Users/COMPUTER/miniforge3/bin/mvt-android", line 8, in <module>
sys.exit(cli())
File "/Users/COMPUTER/miniforge3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/Users/COMPUTER/miniforge3/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/Users/COMPUTER/miniforge3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/COMPUTER/miniforge3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
> Fix error when creating report: csv.Error

- docs/development.md
- mkdocs.yml
- mvt/common/cmd_check_iocs.py
- mvt/common/indicators.py
- mvt/common/module.py
- mvt/common/utils.py
- setup.cfg
Some MVT modules such as the WhatsApp module can be very slow as it was using a naive approach to look for IOCs. The code was checking URLs (potentially more than 100k) against 1000's of IOC domains resulting in a quadratic run-time with hundreds of millions of comparisons as the number of IOCs increases.
This PR add an Aho-Corasick library which allows the efficient search in a string (the URL in this case) for all matches in set of keys (the IOCs). This data structure is perfect for this use case.
A quick measurement shows a 80% performance improvement for a WhatsApp database with 100k entries. The slow path is now the time spent fetching and expanding short URLs. This
can also be sped up significantly by fetching each URL asynchronously. However this would require reworking modules to …
> Optimise domain checking performance

- mvt/android/parsers/dumpsys.py
Without this change the package doesn't get properly reset when a new user starts.
See for example in this excerpt:
```
1 |    Package com.android.bluetooth:
2 |      READ_CONTACTS (allow):
3 |        null=[
4 |          Access: [pers-s] 2022-04-22 13:24:17.577 (-277d5h22m53s447ms)
5 |        ]
6 |      WAKE_LOCK (allow):
7 |        null=[
8 |          Access: [pers-s] 2023-01-24 17:45:49.712 (-1m21s312ms) duration=+3ms
9 |        ]
10 |      GET_USAGE_STATS (default):
11 |        null=[
12 |          Reject: [pers-s]2022-04-22 13:23:53.964 (-277d5h23m17s60ms)
13 |        ]
14 |      BLUETOOTH_CONNECT (allow):
15 |        null=[
16 |          Access: [pers-s] 2022-04-22 13:23:53.988 (-277d5h23m17s36ms)
17 |        ]
18 |  Uid 1027:
19 |    state=pers
20 |    capability=LCMN
21 | …
```
> Improve appops parsing in dumpsys

- .github/workflows/python-package.yml
- .github/workflows/ruff.yml
The ruff Action uses minimal steps to run in ~5 seconds, rapidly providing intuitive GitHub Annotations to contributors.
> Add GitHub Annotions to ruff output

- mvt/android/modules/adb/root_binaries.py
- mvt/ios/modules/backup/manifest.py
- mvt/ios/modules/mixed/sms.py
- mvt/ios/modules/mixed/sms_attachments.py
All detection logic and indicator checking should be in `check_indicators` so that we can re-run new detection logic against previous acquisitions and MVT log files. The `run` stage should just focus on data extraction and parsing.
> Move detection and alerts from run() to check_indicators()

- mvt/ios/data/ios_versions.json
add two additional build numbers based on theapplewiki[0] and wikipedia[1]
Set version to be 17.0
0: https://theapplewiki.com/wiki/Firmware/iPhone/17.x
1: https://en.wikipedia.org/wiki/IOS_17#Release_history
> additional iOS 17.0 build numbers

- mvt/common/cmd_check_iocs.py
- mvt/common/module.py
Sometimes it can be useful to be able to iterate the module classes and get the "slug"/name before the module is actually initialized. Since modules define their custom `slug` as a class variable, `get_slug()` can be called without an instance of the class.
https://github.com/mvt-project/mvt/blob/73104814ba10127b8c3fd64b4f23cc3dbcc0ccb0/mvt/ios/modules/fs/webkit_indexeddb.py#L16-L25
> Make `MVTModule.get_slug()` a classmethod

- .github/workflows/python-package.yml
CI was failing on all external contributions as the default permissions for a workflow running on a forked repo are limited. This allows the job to succeed even if the coverage comment doesn't work.
> Allow PR coverage comment to fail if running on a fork

- .github/workflows/add-issue-to-project.yml
Uses https://github.com/actions/add-to-project to add issues to our board.
> Automatically add issues to development board

- mvt/ios/modules/backup/manifest.py
- mvt/ios/modules/base.py
- mvt/ios/modules/fs/analytics.py
- mvt/ios/modules/fs/cache_files.py
- mvt/ios/modules/fs/safari_favicon.py
- mvt/ios/modules/mixed/calendar.py
- mvt/ios/modules/mixed/calls.py
- mvt/ios/modules/mixed/chrome_favicon.py
- mvt/ios/modules/mixed/chrome_history.py
- mvt/ios/modules/mixed/contacts.py
- mvt/ios/modules/mixed/firefox_favicon.py
- mvt/ios/modules/mixed/firefox_history.py
- mvt/ios/modules/mixed/interactionc.py
- mvt/ios/modules/mixed/safari_browserstate.py
- mvt/ios/modules/mixed/safari_history.py
- mvt/ios/modules/mixed/shortcuts.py
- mvt/ios/modules/mixed/sms.py
- mvt/ios/modules/mixed/sms_attachments.py
- mvt/ios/modules/mixed/tcc.py
- mvt/ios/modules/mixed/webkit_resource_load_statistics.py
- mvt/ios/modules/mixed/whatsapp.py
- tests/ios_fs/test_filesystem.py
Fixes #429 , where `.shm` and `.wal` logs are being left over after tests run.
> Open all iOS sqlite3 databases with immutable=1

- mvt/ios/modules/mixed/sms.py
- mvt/ios/modules/mixed/sms_attachments.py
- tests/ios_backup/test_sms.py
The SMS module was creating noisy entries in the timeline as it would output timeline `sms_read` entries for SMS messages even when no `sms_read` timeline was set. This branch fixes the module so that messages which were not read do not produce an extra entry.
This branch also adds basic indicator checking in the SMS module.
> Impovements for SMS module

- mvt/ios/modules/base.py
This fixes #434 - tested on Ubuntu 22.04, Python 3.11.6
[`uri` was added in Python 3.4](https://docs.python.org/3/library/sqlite3.html) and it looks like this repo already requires >=3.8
I did not add 3.11 to `.github/workflows/python-package.yml` because it causes the CI to fail on safety (outdated pip - requires >=23.3), but unit tests seem to pass on this version
> Add `uri=True` in mvt/ios/modules/base.py

- docs/install.md
- Recommend the use of `pipx` for installing system-wide.
Fixes #447
> Update install docs

- docs/ios/install.md
Updated docs, to replace -d with -v to start usbmuxd
```
$ usbmuxd -V
usbmuxd 1.1.1
$ usbmuxd -f -d
usbmuxd: invalid option -- 'd'
Usage: usbmuxd [OPTIONS]
```
> Usbmuxd debug option changed from -d to -v

- README.md
- docs/introduction.md
- mvt/common/command.py
We regularly hear from individuals or groups who have used MVT with public indicators to check their devices for advanced spyware tools. Unfortunately individuals may get a false sense of security if they do not see any matches from the public indicators.  Not all users may fully understand the limitations of MVT to detect recent or advanced attack without expert support and guidance.
This PR updates the documentation to include links to the Amnesty Security Lab website. The PR also adds a log message at the end of each MVT command which explains the limits of MVT and directs non-expert users to seek expert help if they are concerned about spyware targeting.
> Add docs explaining how to seek expert help for forensic analysis 

- .github/workflows/python-package.yml
- tests/common/test_utils.py
As discovered in #488, builds were not failing when tests were failing :(
> Fail builds on test failure

- mvt/android/modules/androidqf/__init__.py
- mvt/android/modules/androidqf/packages.py
- mvt/android/utils.py
- tests/android_androidqf/test_packages.py
- tests/artifacts/androidqf/packages.json
- tests/common/test_utils.py
- tests/conftest.py
- Detects non-appstore installs
- Match indicators for `packages.json`, same as in the adb Packages module
> Add packages module for androidqf

- .github/workflows/black.yml
The black linter was only being run on pushes to main and not on opened PRs. We should run on both to avoid linting errors after a PR is merged.
> Run black linter on pull requests

- src/mvt/common/indicators.py
- tests/artifacts/generate_stix.py
- tests/common/test_indicators.py
This PR reworks #465 which was started by [renini](https://github.com/renini).
The initial PR had support for specifying IP address in CIDR format. I've remove this for now as it could risk making MVT slow if large CIDRs are specified with thousands or millions of IPs. 
This first version supports IP addresses by treated as domains internally in MVT which will automatically be matching in existing `check_domain` and `check_url` functions.
Closes #465.
> Add basic support for IP indicators in MVT

- src/mvt/android/artifacts/dumpsys_adb.py
This commit fixes a crash in the ADB module when no keys were parsed. We should return an empty list by default.
> Fix crash when handling empty adb key list

- src/mvt/android/modules/androidqf/packages.py
- tests/android_androidqf/test_packages.py
This PR adds additional detections for Android security packages which have been disabled.
It also adds full detections for certain suspicious app installs to make these easier to identify in the MVT output as requiring  further investigation. The new code will also de-duplicate detections to only be written once per app and detection (app name, cert etc.).
> Add additional detections for suspicious packages

- src/mvt/android/artifacts/dumpsys_adb.py
- tests/android/test_artifact_dumpsys_adb.py
- tests/artifacts/android_data/dumpsys_adb_xml.txt
Also fixes a parsing bug when a key is saved without a username.
Closes #604.
> Add support for parsing ADB keystore in XML format

- src/mvt/android/artifacts/tombstone_crashes.py
This commit fixes bug a where default values were dropped when parsing protobuf tombstone files. This meant that important fields such as UID would be dropped with set to "0", the default value for an integer field.
Passing `include_default_values` seems to fix the issue!
> Include default values when parsing tombstone protobuf files

- src/mvt/android/artifacts/dumpsys_adb.py
Apparently sometimes there are some non base64 data in the ADB keys on Android, not sure why, but here is a fix to handle that properly, in that case the key will be in results but there is no fingerprint as it wasn't possible to decode it.
> Fixes #229 bug
